### ISSUE TITLE
Mac字体问题

### ISSUE THREAD

**Issue by akilius778** [Soanguy/Typora-Theme-Neumorphism#1]
主题很好看～但是woff2格式字体好像没法用mac的字体集安装，只能自己把每个字体转换成ttf再安装，否则打开主题会变成全隶书🥹有什么办法能够解决呢？如果能够选择换成本地别的字体也可以！

**Comment by Soanguy** [comment]
我记得css是支持woff2格式的字体的。默认把所有的文件都放到typora的themes文件夹下应该就可以显示了。是不需要额外进行安装的。当然，如果行不通的话可以直接搜索 汉仪花冠（正文字体，或者霞鹜文楷也可以）发自我的 iPhone在 2023年1月30日，11:33，akilius778 ***@***.***> 写道：﻿
主题很好看～但是woff2格式字体好像没法用mac的字体集安装，只能自己把每个字体转换成ttf再安装，否则打开主题会变成全隶书🥹有什么办法能够解决呢？如果能够选择换成本地别的字体也可以！

**Comment by Soanguy** [comment]
把两个 css 文件和 fonts 文件夹放到 themes 文件夹下就okay了。

标题字体：Old Standard TT（或者Didot）、方正聚珍新仿简繁
正文字体：Bellota、汉仪花冠（或者霞鹜文楷）
强调字体：Old Standard TT（或者Didot）、方正楷体（或者华文楷体）
代码字体：Anonymous、汉仪花冠
