### ISSUE TITLE
二级列表没有正常显示

### ISSUE THREAD

**Issue by HuaWang135608** [Soanguy/Typora-Theme-Neumorphism#10]
菜单栏里没有显示，下属的三级列表显示续借的上一个二级列表的序号

![屏幕截图 2023-09-03 224348](https://github.com/Soanguy/Typora-Theme-Neumorphism/assets/84295489/68ee3841-048b-4723-a4a6-975a0b5576cd)

**Comment by Soanguy** [comment]
菜单栏？你是说侧边栏吧。你想要的形式是这种吗？

```
----------------------------|-----------
侧边栏                       |   正
                            |   
Chapter I blabla blabla     |   文
  SectionII blabla blabla   |   
    1.1 blablabla blabla    |   区
----------------------------|-----------
```

**Comment by HuaWang135608** [comment]
> 菜单栏？你是说侧边栏吧。你想要的形式是这种吗？
> 
> ```
> ----------------------------|-----------
> 侧边栏                       |   正
>                             |   
> Chapter I blabla blabla     |   文
>   SectionII blabla blabla   |   
>     1.1 blablabla blabla    |   区
> ----------------------------|-----------
> ```

是侧边栏，二级列表在侧边栏没有正常显示；正常显示的是这样的；而且计数也是有问题的，没有重新计数

![屏幕截图 2023-09-04 092236](https://github.com/Soanguy/Typora-Theme-Neumorphism/assets/84295489/8b414505-c5f1-4b8c-8c14-00d7c79ac171)

**Comment by HuaWang135608** [comment]
抱歉，我的问题😂，二级列表放在无序列表后面了
