### ISSUE TITLE
我想将显示的页面调宽一些，请问作者大大该如何实现呢？

### ISSUE THREAD

**Issue by glxaa** [Soanguy/Typora-Theme-Neumorphism#11]
我想将显示的页面调宽一些，请问作者大大该如何实现呢？
它有点窄了，我的代码显示一部分后就得换行显示，图片也会缩小。所以假如让这个主题的页面变宽一点，该如何实现呢？

**Comment by Soanguy** [comment]
<img width="1259" alt="Snipaste_2403140918" src="https://github.com/Soanguy/Typora-Theme-Neumorphism/assets/24608949/c462bbb0-61fa-4bfd-b649-bd56c92098b9">

在对应的主题 css 文件中，找到上图的代码。修改一下数字就好了。
