### ISSUE TITLE
请教关于展示的模版页的语法

### ISSUE THREAD

**Issue by bingyang-lei** [Soanguy/Typora-Theme-Neumorphism#12]
想问下展示的模版页标题（夕既）旁边的时间和日期怎么创建呀，语法是什么
![屏幕截图 2024-03-15 174949](https://github.com/Soanguy/Typora-Theme-Neumorphism/assets/152671156/060b3704-f55a-42d3-9855-ca710279115a)
以及如果方便的话能把这个图片里的源代码分享出来嘛？感觉这本身就是个很不错的模版

**Comment by Soanguy** [comment]
```
# 标题 `小标题,实际是代码`

> 引用内容
>
> - 列表
>
> - [ ] 代办列表
>
> - [x] 已完成列表
>
> <span style='color:red'>变色内容</span>
```

**Comment by Soanguy** [comment]
除了代办列表的那个，其他的都是标准语法。你可以试试。

**Comment by bingyang-lei** [comment]
OKOK非常感谢！那个小标题是代码块语法不说还真是看不出来（捂脸）
