### ISSUE TITLE
主题反馈

### ISSUE THREAD

**Issue by ghost** [Soanguy/Typora-Theme-Neumorphism#2]
问题反馈：
表格中内容的下划线无法显示
建议：
1.建议移除鼠标移动到表格上出现的整行的颜色加深标识，或者更换成其他颜色，当前的颜色与主题整体配色不太合适
2.下划线可以更改为其他符合主题配色的颜色
3.菜单页面的选中框建议更改颜色

**Comment by Soanguy** [comment]
感谢建议。

**Comment by ghost** [comment]
建议不是很重要的东西，作者考虑一下就行，主要是那个表格里面的下划线不会显示，看着很难受，强迫症都犯了

**Comment by Soanguy** [comment]
那个是我代码的问题，我忘记设定他们的层级关系了。你可以先试着加入

```
body #write u{z-index:0;}
```

看看有没有改变。

**Comment by ghost** [comment]
嗯，可以显示了
