### ISSUE TITLE
问题反馈

### ISSUE THREAD

**Issue by ghost** [Soanguy/Typora-Theme-Neumorphism#3]
任务列表中，鼠标移动到任务列表内容文字上时，文字会加深显示
选中列表文字时显示颜色与加深颜色相同，建议将任务列表加深颜色与选中文字颜色区别开

**Comment by Soanguy** [comment]
感谢反馈。我试了一下，在暗夜模式下确实如此。当时设定的是当任务列表的hover色和seleted色设置成了相同的。如果比较紧急的话可以试着找到 `body #write .task-list-item input + p:hover` 然后修改他的 background 属性值为你喜欢的颜色即可。比如：

```
body #write .task-list-item input + p:hover {
    background: #207f4c; /* 此处修改颜色值即可 */
}
```

之后会再度修改这个问题，等我找到比较合适的颜色。

**Comment by ghost** [comment]
暗夜模式我不清楚，但白天模式是这样的







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月21日(星期二) 晚上10:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Soanguy/Typora-Theme-Neumorphism] 问题反馈 (Issue #3)





 
感谢反馈。我试了一下，在暗夜模式下确实如此。当时设定的是当任务列表的hover色和seleted色设置成了相同的。如果比较紧急的话可以试着找到 body #write .task-list-item input + p:hover 然后修改他的 background 属性值为你喜欢的颜色即可。比如：
 body #write .task-list-item input + p:hover {     background: #207f4c; /* 此处修改颜色值即可 */ }  
之后会再度修改这个问题，等我找到比较合适的颜色。
