### ISSUE TITLE
显示问题

### ISSUE THREAD

**Issue by h304192** [Soanguy/Typora-Theme-Neumorphism#5]
导出为HTML后光标悬停到标题会出现显示问题
![屏幕截图 2023-03-21 184105](https://user-images.githubusercontent.com/109783518/226582843-567e8d2c-b30b-484e-8c69-08c721e226b1.png)

**Comment by Soanguy** [comment]
这个并不是bug，这本来是作为特性存在的。如果在您的电脑上能够在光标移入时如动画般出现和移出时自动消失，那么他便没有问题。

如果您不喜欢这个特性，您可以在 css 中找到 `body #write h4::after` 这段代码下的

```
-webkit-transition: max-width ease-in-out 1s;
-moz-transition: max-width ease-in-out 1s;
transition: max-width ease-in-out 1s;
```

这一串代码，然后注释掉就可以了。

**Comment by h304192** [comment]
问题是动画和内容没有对齐，动画没有正常显示标点符号

**Comment by Soanguy** [comment]
我在使用了标点符号后确实发现了这个问题，这个目前仅仅修改 css 是无法解决的。这个特性的实现方式是获取 typora 的标题 id后再以 hover 的形式展示出来。但是目前 typora 在生成标题 id 的时候，似乎只会生成含有汉字或者字母的内容。他会排除掉一些标点符号。所以可能目前来看，只能是：

- 在标题处尽可能的不使用标点符号；
- 如同上次回复的内容，直接删除掉该特性。他只是作为一种展示方式存在，删除不会影响任何内容。
