### ISSUE TITLE
打开多个文件后，状态栏疯狂闪动

### ISSUE THREAD

**Issue by XuLiang134** [Soanguy/Typora-Theme-Neumorphism#6]

**Comment by XuLiang134** [comment]
frame.js:1          GET typora://userData\themes\neumorphism.user.css net::ERR_FILE_NOT_FOUND

**Comment by Soanguy** [comment]
这个文件本身就是不存在的。你的系统是windows还是macos？我先看一下是不是因为js代码的原因

**Comment by Soanguy** [comment]
我在macOS 上试了一下打开 5个文件，没有发现问题。可能是 windows ？不过我现在的windows 上的typora 是未激活，只能打开一个文件。

**Comment by XuLiang134** [comment]
我的是Windows ，激活了，开一个文件没问题，开两个就看概率，

**Comment by XuLiang134** [comment]
我删除了所有主题，然后重新导入这一个就ok了，很喜欢你这个主题

**Comment by Soanguy** [comment]
谢谢。目前是没有问题了是么？
因为我的windows上的没有激活。有问题的话，我晚上回去换个电脑再看一下。

**Comment by XuLiang134** [comment]
没有问题了，
