### ISSUE TITLE
打印样式Bug？

### ISSUE THREAD

**Issue by Jagerx** [Soanguy/Typora-Theme-Neumorphism#7]
<img width="834" alt="image" src="https://user-images.githubusercontent.com/42521386/235637791-dbad662a-d80e-435d-a1cf-d61d33fb06f4.png">

本来的阴影，成了两个大框，是不是Bug呢

**Comment by Soanguy** [comment]
我在 Mac 上导出后没有发现。可能是在 Windows 上如此。不过设计之初就没有专门为导出为PDF做优化。可以试着在 css 代码的最后一行添加如下代码来禁止阴影：

```
@media print{
    pre.md-fences{
        box-shadow: none!important;
    }
}
```

**Comment by Jagerx** [comment]
好的，我试试禁止阴影，感谢。

确实是导出PDF出现问题。电脑是MAC Air M2，系统Ventura 13.3.1，Typora 1.5.14 (6769)
