### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by HuaWang135608** [Soanguy/Typora-Theme-Neumorphism#9]
是将文件解压后的文件夹放到主题目录下，还是复制几个特定的文件就行？

**Comment by Soanguy** [comment]
一并丢到主题目录下就可以了。 然后重启软件，在选择主题的那个地方就可以看到这两个主题了

**Comment by HuaWang135608** [comment]
> 一并丢到主题目录下就可以了。 然后重启软件，在选择主题的那个地方就可以看到这两个主题了

感谢回复。将解压后的两个 css 文件和 fonts 文件夹放到主题目录下就可以了。
主题很好看~
